import { qData } from '../components/questionData';
export declare class UIController {
    private static instance;
    private static configuredRoot;
    private root;
    private landingContainerId;
    landingContainer: HTMLElement;
    private gameContainerId;
    gameContainer: HTMLElement;
    private endContainerId;
    endContainer: HTMLElement;
    private starContainerId;
    starContainer: HTMLElement;
    private chestContainerId;
    chestContainer: HTMLElement;
    private questionsContainerId;
    questionsContainer: HTMLElement;
    private feedbackContainerId;
    feedbackContainer: HTMLElement;
    private answersContainerId;
    answersContainer: HTMLElement;
    private answerButton1Id;
    private answerButton1;
    private answerButton2Id;
    private answerButton2;
    private answerButton3Id;
    private answerButton3;
    private answerButton4Id;
    private answerButton4;
    private answerButton5Id;
    private answerButton5;
    private answerButton6Id;
    private answerButton6;
    private playButtonId;
    private playButton;
    private loadingScreenId;
    private progressBarId;
    private chestImgId;
    private chestImg;
    nextQuestion: any;
    contentLoaded: boolean;
    private gameReady;
    private skipStartScreen;
    qStart: any;
    shown: boolean;
    stars: any[];
    shownStarsCount: number;
    starPositions: Array<{
        x: number;
        y: number;
    }>;
    qAnsNum: number;
    allStart: number;
    buttons: any[];
    private buttonPressCallback;
    private startPressCallback;
    buttonsActive: boolean;
    private devModeCorrectLabelVisibility;
    private devModeBucketControlsEnabled;
    animationSpeedMultiplier: number;
    externalBucketControlsGenerationHandler: (container: HTMLElement, clickCallback: () => void) => void;
    private createFallbackElement;
    private resetRuntimeState;
    private getElementById;
    private getElementByIdOrSelector;
    static ConfigureRoot(root: Document | ShadowRoot | HTMLElement): void;
    static Reset(): void;
    private init;
    private initializeStars;
    SetAnimationSpeedMultiplier(multiplier: number): void;
    SetCorrectLabelVisibility(visible: boolean): void;
    SetBucketControlsVisibility(visible: boolean): void;
    static OverlappingOtherStars(starPositions: Array<{
        x: number;
        y: number;
    }>, x: number, y: number, minDistance: number): boolean;
    private initEventListeners;
    private canShowGameFromLanding;
    private maybeAutoStartGame;
    showOptions(): void;
    private enableAnswerButton;
    static SetFeedbackText(nt: string): void;
    private showLanding;
    static ShowEnd(): void;
    private showGame;
    static SetFeedbackVisibile(visible: boolean, isCorrect: boolean): void;
    static ReadyForNext(newQ: qData, reGenerateItems?: boolean): void;
    static ShowAudioAnimation(playing?: boolean): void;
    static ShowQuestion(newQuestion?: qData): void;
    static AddStar(): void;
    static ChangeStarImageAfterAnimation(): void;
    private answerButtonPress;
    static ProgressChest(): void;
    static SetContentLoaded(value: boolean): void;
    static SetSkipStartScreen(value: boolean): void;
    static SetGameReady(value: boolean): void;
    static SetLoadingVisible(visible: boolean): void;
    static SetLoadingProgress(progress: number): void;
    static SetButtonPressAction(callback: Function): void;
    static SetStartAction(callback: Function): void;
    static SetExternalBucketControlsGenerationHandler(handler: (container: HTMLElement, clickCallback: () => void) => void): void;
    static getInstance(): UIController;
}
