import { qData } from '../components/questionData';
import { bucket } from '../assessment/bucketData';
export declare class AnalyticsEvents {
    protected static uuid: string;
    protected static userSource: string;
    protected static clat: any;
    protected static clon: any;
    protected static gana: any;
    protected static latlong: any;
    protected static dataURL: any;
    protected static appVersion: any;
    protected static contentVersion: any;
    protected static assessmentType: string;
    static instance: AnalyticsEvents;
    private constructor();
    static getInstance(): AnalyticsEvents;
    static setAssessmentType(assessmentType: string): void;
    static getLocation(): void;
    static linkAnalytics(newgana: any, dataurl: any): void;
    static setUuid(newUuid: string, newUserSource: string): void;
    static sendInit(appVersion: string, contentVersion: string): void;
    static getAppLanguageFromDataURL(appType: string): string;
    static getAppTypeFromDataURL(appType: string): string;
    static sendLocation(): void;
    static sendAnswered(theQ: qData, theA: number, elapsed: number): void;
    static sendBucket(tb: bucket, passed: boolean): void;
    static sendFinished(buckets: bucket[], basalBucket: number, ceilingBucket: number): void;
    static sendDataToThirdParty(score: number, uuid: string, requiredScore: Number, nextAssessment: string): void;
    static calculateScore(buckets: bucket[], basalBucketID: number): number;
    static getBasalBucketID(buckets: bucket[]): number;
    static getCeilingBucketID(buckets: bucket[]): number;
    static joinLatLong(lat: string, lon: string): string;
}
