version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  s3-deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./
          to: 's3://assessment-and-survey-development'

  s3-deploy-prod:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY
          aws-region: AWS_PROD_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ./
          to: 's3://assessment-and-survey-production'

workflows:
  s3-deploy-workflow:
    jobs:
      - s3-deploy:
          filters:
            branches:
              only:
                - develop
      - s3-deploy-prod:
          filters:
            branches:
              only:
                - main
