import { App } from './App';
import { UnityBridge } from './utils/unityBridge';
import { PubSub } from '@curiouslearning/core';
export declare abstract class BaseQuiz extends PubSub {
    protected app: App;
    protected quizEndData: any;
    id: string;
    type: string;
    score: number;
    startTime: number;
    endTime: number;
    dataURL: string;
    unityBridge: UnityBridge;
    devModeAvailable: boolean;
    isInDevMode: boolean;
    isCorrectLabelShown: boolean;
    isBucketInfoShown: boolean;
    isBucketControlsEnabled: boolean;
    animationSpeedMultiplier: number;
    devModeToggleButtonContainerId: string;
    devModeToggleButtonContainer: HTMLElement;
    devModeToggleButtonId: string;
    devModeToggleButton: HTMLButtonElement;
    devModeModalId: string;
    devModeSettingsModal: HTMLElement;
    devModeBucketGenSelectId: string;
    devModeBucketGenSelect: HTMLSelectElement;
    devModeCorrectLabelShownCheckboxId: string;
    devModeCorrectLabelShownCheckbox: HTMLInputElement;
    devModeBucketInfoShownCheckboxId: string;
    devModeBucketInfoShownCheckbox: HTMLInputElement;
    devModeBucketInfoContainerId: string;
    devModeBucketInfoContainer: HTMLElement;
    devModeBucketControlsShownCheckboxId: string;
    devModeBucketControlsShownCheckbox: HTMLInputElement;
    devModeAnimationSpeedMultiplierRangeId: string;
    devModeAnimationSpeedMultiplierRange: HTMLInputElement;
    devModeAnimationSpeedMultiplierValueId: string;
    devModeAnimationSpeedMultiplierValue: HTMLElement;
    constructor();
    hideDevModeButton(): void;
    abstract handleBucketGenModeChange(event: Event): void;
    abstract handleCorrectLabelShownChange(): void;
    abstract handleBucketInfoShownChange(): void;
    abstract handleBucketControlsShownChange(): void;
    abstract handleAnimationSpeedMultiplierChange(): void;
    toggleDevModeModal: () => void;
    abstract Run(applink: App): void;
    abstract handleAnswerButtonPress(ans: number, elapsed: number): void;
    abstract HasQuestionsLeft(): boolean;
    start(): void;
    onEnd(): void;
}
